//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorSalud
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DoctorSalud_Entities : DbContext
    {
        public DoctorSalud_Entities()
            : base("name=DoctorSalud_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cardiologo> Cardiologo { get; set; }
        public virtual DbSet<CitaDS> CitaDS { get; set; }
        public virtual DbSet<MedicinaInterna> MedicinaInterna { get; set; }
        public virtual DbSet<Nutriologo> Nutriologo { get; set; }
        public virtual DbSet<Oftalmologo> Oftalmologo { get; set; }
        public virtual DbSet<PacienteDS> PacienteDS { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<RolMenu> RolMenu { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<RecepcionistaDS> RecepcionistaDS { get; set; }
        public virtual DbSet<SucursalDS> SucursalDS { get; set; }
        public virtual DbSet<EPI_A_Heredofamiliares> EPI_A_Heredofamiliares { get; set; }
        public virtual DbSet<EPI_A_NoPatologicos> EPI_A_NoPatologicos { get; set; }
        public virtual DbSet<EPI_A_Patologicos> EPI_A_Patologicos { get; set; }
        public virtual DbSet<EPI_AparatosSistemas> EPI_AparatosSistemas { get; set; }
        public virtual DbSet<EPI_Audiologia> EPI_Audiologia { get; set; }
        public virtual DbSet<EPI_Cardiologia> EPI_Cardiologia { get; set; }
        public virtual DbSet<EPI_DictamenAptitud> EPI_DictamenAptitud { get; set; }
        public virtual DbSet<EPI_ExploracionFisica> EPI_ExploracionFisica { get; set; }
        public virtual DbSet<EPI_Laboratorio> EPI_Laboratorio { get; set; }
        public virtual DbSet<EPI_Odontologia> EPI_Odontologia { get; set; }
        public virtual DbSet<Epi_Oftalmologia> Epi_Oftalmologia { get; set; }
        public virtual DbSet<EPI_SignosVitales> EPI_SignosVitales { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<SignosVitalesDS> SignosVitalesDS { get; set; }
        public virtual DbSet<Farmacia> Farmacia { get; set; }
    }
}
