//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorSalud
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DoctorSalud_Entities : DbContext
    {
        public DoctorSalud_Entities()
            : base("name=DoctorSalud_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cardiologo> Cardiologo { get; set; }
        public virtual DbSet<CitaDS> CitaDS { get; set; }
        public virtual DbSet<MedicinaInterna> MedicinaInterna { get; set; }
        public virtual DbSet<Nutriologo> Nutriologo { get; set; }
        public virtual DbSet<Oftalmologo> Oftalmologo { get; set; }
        public virtual DbSet<PacienteDS> PacienteDS { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<RolMenu> RolMenu { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<RecepcionistaDS> RecepcionistaDS { get; set; }
        public virtual DbSet<SucursalDS> SucursalDS { get; set; }
    }
}
